behaviors:
  AUV:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 5.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000

